### PR TITLE
Pass system to darwinSystem rather than eval-config.

### PR DESCRIPTION
**Pull request by dhess**
This allows us to specify what kind of darwinSystem we want to build, rather than determining it at evaluation time.

### CODE REVIEW

**Comment by bphenriques** [comment]
This should fix #319

**Comment by dhess** [comment]
FYI, I'm not quite sure why the build failed. I've been using this successfully in my fork since I submitted this PR.

**Comment by domenkozar** [comment]
This is a good example how https://github.com/NixOS/nix/issues/3843 would simplify flakes and remove the need to hardcode system like in this case.

**Comment by domenkozar** [comment]
@dhess could you rebase and check if tests pass?

**Comment by dhess** [comment]
Done.

**Comment by domenkozar** [comment]
I've added some design thoughts to https://github.com/NixOS/nix/issues/3843#issuecomment-915177908

**Comment by domenkozar** [comment]
```
error: anonymous function at /nix/store/nb2kapr1yf12ra2x3jmdbm2lwfh9c1pr-source/eval-config.nix:3:1 called with unexpected argument 'system'

       at /nix/store/nb2kapr1yf12ra2x3jmdbm2lwfh9c1pr-source/flake.nix:10:58:

            9|
           10|       darwinSystem = { modules, inputs ? {}, ... }@args: self.lib.evalConfig (args // {
             |                                                          ^
           11|         inputs = { inherit nixpkgs; darwin = self; } // inputs;
```

**Comment by dhess** [comment]
I'll try to take a look at this over the weekend.

**Comment by emilazy** [comment]
This PR worked perfectly for me, thank you! I think @domenkozar's error must be related to issues with specifying this fork in `flake.nix`:

* the excerpted code `darwinSystem = { modules, inputs ? {}, ... }@args:` doesn't appear in the PR branch's `flake.nix`;
* the `/nix/store/nb2kapr1yf12ra2x3jmdbm2lwfh9c1pr-source` source path matches what I get for the current upstream nix-darwin flake, whereas this PR has the source path `/nix/store/b8igm25p67844z4gylbmskndi7r8r607-source` (you can check with `nix flake metadata …`).

The error looks what you'd get passing `system` to the `darwinSystem` from current nix-darwin.

**Comment by dhess** [comment]
Good catch.

I'm not sure how to fix this, or whether it's even worth bothering, given that it won't be a problem once it's merged. I'll wait to hear from @LnL7, in any case.

**Comment by emilazy** [comment]
FWIW, `darwin.url = "github:hackworthltd/nix-darwin/darwinSystem";` was how I successfully tested this PR with flakes.

**Comment by LnL7** [comment]
Ah I see, now the error makes sense. It seems like the `nix registry` override that the tests use doesn't have precedence anymore over the input defined in the flake.

**Comment by LnL7** [comment]
@dhess I can push a fix for the tests if you allow edits from maintainers.

**Comment by dhess** [comment]
> @dhess I can push a fix for the tests if you allow edits from maintainers.

Sorry for being dense, but how do I do that?

**Comment by LnL7** [comment]
There should be a checkbox in the sidebar. I would expect it to be checked by default however, maybe I my push attempt was incorrect?

**Comment by dhess** [comment]
I don't see that option. Perhaps it's because the branch is from a repo owned by an org and not an individual?

**Comment by LnL7** [comment]
Weird, guess it must be something like that. Well you can just cherry-pick it from https://github.com/LnL7/nix-darwin/commits/flakes-test then. 😄

**Comment by dhess** [comment]
Or you could just merge your branch :) I don't care either way, whatever you prefer.

**Comment by dhess** [comment]
Excellent, thanks!

**Pull request merged**
