### PR TITLE
flake: match NixOS definition of `nixpkgs.flake.source`

### PR DESCRIPTION
**Pull request by emilazy**
Closes: #1082

### CODE REVIEW

**Comment by emilazy** [comment]
This is still wrong because Nixpkgs isn’t necessarily from our `nixpkgs` input at all and I forgot all the lessons I learned in https://github.com/LnL7/nix-darwin/pull/723 and everything is sad and I need to do something else here. :(

**Comment by sellout** [comment]
FWIW, my configuration builds successfully with this change. Good luck with finding a solution that satisfies you!

**Comment by Enzime** [comment]
How does this PR relate to #1076?

**Comment by antoineco** [comment]
I'm admitedly confused about this one. The error was

> `'nix.registry.nixpkgs.to.path' is defined multiple times`

but all this PR does is type the value of `nixpkgs.flake.source` from a flake attrset to a string representation of its path in the Nix store.

How does this prevent said option to be set multiple times?

**Review by antoineco — COMMENTED** [review]
I tried this branch with an overriden `nixpkgs`:

```nix
{
  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.2405"; # nixos-24.05

    nix-darwin = {
      url = "github:emilazy/nix-darwin/push-zovpmlzlzvvm";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs =
    {
      self,
      nixpkgs,
      nix-darwin,
    }:
    {
      darwinConfigurations = {
        myhost = nix-darwin.lib.darwinSystem {
          modules = [
            {
              nixpkgs.hostPlatform = "aarch64-darwin";
              system.stateVersion = 5;

              nix.registry.nixpkgs.flake = nixpkgs;
            }
          ];
        };
      };
    };
}
```

No error for me 👍 The resulting registry contains the expected entry:

```json
{
  "flakes": [
    {
      "exact": true,
      "from": {
        "id": "nixpkgs",
        "type": "indirect"
      },
      "to": {
        "lastModified": 1725930920,
        "narHash": "sha256-RVhD9hnlTT2nJzPHlAqrWqCkA7T6CYrP41IoVRkciZM=",
        "path": "/nix/store/20yis5w6g397plssim663hqxdiiah2wr-source",
        "rev": "44a71ff39c182edaf25a7ace5c9454e7cba2c658",
        "revCount": 635017,
        "type": "path"
      }
    }
  ],
  "version": 2
}
```

**Comment by emilazy** [comment]
Sorry for the dramatic reaction, I have just been repeatedly burned by Nixpkgs mismatch issues :)

I will try to explain what’s going on here and what issues there still are tomorrow.

**Comment by emilazy** [comment]
Didn’t end up getting around to writing down all the moving parts here today; will try to do so in the next couple days. The tl;dr is that this PR won’t make anything worse and should be okay to merge, but the whole way this is set currently is quite incorrect in a way that can result in pretty bad outcomes (e.g. pinning a vulnerable version of Nixpkgs even though your system uses a good one, or even getting a different release branch entirely). I think the upstream NixOS version of this is also broken in a similar but less likely to trigger way (due to the fact that it’s in the Nixpkgs repository itself). I’m still thinking about the best way to resolve the issues; https://github.com/LnL7/nix-darwin/pull/1076 is not strictly related, but could potentially also use some rethinking depending on what ends up seeming best (and I should adjust it to fix https://github.com/LnL7/nix-darwin/issues/792 anyway).

**Review by Enzime — APPROVED** [review]

**Pull request merged**
