### PR TITLE
Improve Karabiner-Elements installer reliability

### LINKED ISSUE #564: Karabiner Elements stops working after darwin-rebuild switch
I use Karabiner Elements to turn my caps lock into a "hyper" key. I've been using it via homebrew for years without issue.

Moving over to nix and nix-darwin, it works most of the time, but if I update my flake inputs and `darwin-rebuild switch`, I find that Karabiner Elements stops working until I reboot.

I haven't found anything that will get it working again without a reboot:

- manually restarting relevant launchd agents (listed below)
- killing and restarting relevant processes found in Activity Monitor / `ps` / reading through the launchd plists
- using the `Restart Karabiner-Elements` button in the app's GUI
- resetting and re-enabling its "privacy & security" settings: `tccutil reset All org.pqrs.Karabiner-Elements.Preferences`

```console
$ ls -l ~/Library/LaunchAgents/*karabiner*
-r--r--r-- 1 n8henrie staff 517 Oct 23 12:22 /Users/n8henrie/Library/LaunchAgents/org.nixos.activate_karabiner_system_ext.plist
-r--r--r-- 1 n8henrie staff 646 Nov  5 16:37 /Users/n8henrie/Library/LaunchAgents/org.pqrs.karabiner.agent.karabiner_grabber.plist
-r--r--r-- 1 n8henrie staff 648 Nov  5 16:37 /Users/n8henrie/Library/LaunchAgents/org.pqrs.karabiner.agent.karabiner_observer.plist
-r--r--r-- 1 n8henrie staff 605 Nov  5 16:37 /Users/n8henrie/Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist
-r--r--r-- 1 n8henrie staff 512 Oct 23 13:27 /Users/n8henrie/Library/LaunchAgents/org.pqrs.karabiner.karabiner_session_monitor.plist
```

Any ideas? I seem to recall that with my Homebrew installation, after a reboot I would get a notification that it had been updated. Perhaps it just *has* to reboot, but homebrew deferred activating the new version until a reboot?

### PR DESCRIPTION
**Pull request by Enzime**
Hopefully fixes #564

### CODE REVIEW

**Comment by vamega** [comment]
Updating my flake input to your branch, and then ran

```
nix flake lock
# It printed a message about nix-darwin input being updated
darwin-rebuild --flake switch '.#<my hostname>' switch
```

Doesn't seem like anything is broken, but not sure if anything got fixed.
I'll probably need to remove karabiner from my flake, reinstall from the homebrew cask.

Then maybe try to uninstall cask, and reinstall this to see if it "fixes" things.
Probably need to do once to ensure I can replicate the broken issue, and then once again with this change applied to see if it fixes things.

I'll try to do it this weekend, don't think I'll have the time to fiddle with this during the week.

**Comment by n8henrie** [comment]
@Enzime Hard to test right now because it's been an intermittent problem for me. Just did a `nix flake update && darwin-rebuild switch` and karabiner continues working fine.

Have you found a consistent way to provoke the issue? If you can help me recreate it consistently I'll be happy to test.

**Comment by Enzime** [comment]
The easiest repro for me would be running `darwin-rebuild switch --override-input nixpkgs ~/nixpkgs` with a different Karabiner-Element, then switching back and forth between that and not having that flag.

**Comment by n8henrie** [comment]
Good point. I have been tracking `nixpkgs-22.11` and just added an overlay to pull in KE from unstable, and that provoked the behavior, and the referenced PR seems to work -- or at least helps (a lot).

Even with these changes it seems that when KE changes, it needs to prompt for new permissions, and the nix-darwin processes don't work the first time maybe due to permissions not yet being in effect. However, once permissions are granted, running `darwin-rebuild switch` a second time (with no changes to config or inputs) and things are working again.

Here's the process I went through:

1. enable unstable KE
2. verify KE stops working
3. revert back to stable KE
4. verify KE still isn't working
5. check out `improve-karabiner-elements`
6. `darwin-rebuild switch`
7. KE working again
8. re-enable unstable KE
9. `darwin-rebuild switch`
10. KE prompts for permissions, not working, but repeating `darwin-rebuild switch` with no other changes it works (no reboot)
11. re-disable unstable KE
12. 10. KE prompts for permissions, not working, but repeating `darwin-rebuild switch` with no other changes it works (no reboot)

**Comment by Enzime** [comment]
@n8henrie thanks for testing it, in my testing I believe that after KE prompts for permissions if you wait around a minute for KE to start up you won't actually need to run a `darwin-rebuild switch`

**Comment by Enzime** [comment]
@domenkozar can you take a look at this when you have a chance?

**Comment by vamega** [comment]
I just updated my own config, and it pulled in a new Karabiner Elements.
I got asked to give the new binaries permissions, but as soon as I did that the input remapping was working correctly.

Looks like it's working for me!

**Review by domenkozar — APPROVED** [review]

**Pull request merged**
