### PR TITLE
Add support for submodules in flakes

### PR DESCRIPTION
**Pull request by n8henrie**
Fixes https://github.com/LnL7/nix-darwin/issues/549

### CODE REVIEW

**Comment by n8henrie** [comment]
Now seeing an issue locally:

```console
$ darwin-rebuild switch --flake ~/.dotfiles?submodules=1
building the system configuration...
error: hash '6fe08be311b28874c781d4caab7f2a130e2814bd?submodules=1' has wrong length for hash type 'sha1'
```

**Comment by n8henrie** [comment]
Hmm, don't seem to be able to reproduce that error again.

- `darwin-rebuild switch --flake git+file:///$HOME/.dotfiles?submodules=1`
- `darwin-rebuild switch --flake .?submodules=1`
- `darwin-rebuild switch --flake ~/.dotfiles?submodules=1`

All working.

**Comment by n8henrie** [comment]
I got the `hash '6fe08be311b28874c781d4caab7f2a130e2814bd?submodules=1' has wrong length` error again. Something to do with having a clean workspace I think, using the cached git repo?

In this case `nix flake metadtata`:

```console
$ nix --extra-experimental-features 'nix-command flakes' flake metadata --json -- '/Users/n8henrie/.dotfiles?submodules=1' | jq
{
  "description": "n8henrie's system configuration",
  "lastModified": 1666540926,
  "locked": {
    "lastModified": 1666540926,
    "narHash": "sha256-x7yszRqlps3HmflZ4/vXtoC9JVSOB+b4RTQhzGW01DM=",
    "ref": "refs/heads/master",
    "rev": "3afc1004fa37b760e66183519c79458843e7d533",
    "revCount": 863,
    "submodules": true,
    "type": "git",
    "url": "file:///Users/n8henrie/.dotfiles"
  },
  "locks": {
    "nodes": {
      "darwin": {
        "inputs": {
          "nixpkgs": [
            "nixpkgs-darwin"
          ]
        },
        "locked": {
          "lastModified": 1666295985,
          "narHash": "sha256-QIoudC90FbEyCiFPP2qJe8QUeWrUMmRfUaKfmpZiVL0=",
          "type": "git",
          "url": "file:///Users/n8henrie/git/nix-darwin"
        },
        "original": {
          "type": "git",
          "url": "file:///Users/n8henrie/git/nix-darwin"
        }
      },
      "home-manager": {
        "inputs": {
          "nixpkgs": [
            "nixpkgs"
          ]
        },
        "locked": {
          "lastModified": 1665996265,
          "narHash": "sha256-/k9og6LDBQwT+f/tJ5ClcWiUl8kCX5m6ognhsAxOiCY=",
          "owner": "nix-community",
          "repo": "home-manager",
          "rev": "b81e128fc053ab3159d7b464d9b7dedc9d6a6891",
          "type": "github"
        },
        "original": {
          "owner": "nix-community",
          "ref": "release-22.05",
          "repo": "home-manager",
          "type": "github"
        }
      },
      "nixpkgs": {
        "locked": {
          "lastModified": 1666450137,
          "narHash": "sha256-3lZF7fiKdFlXACh1m9Z1jpsey8FlJH9uVgZE2zqnpkE=",
          "owner": "nixos",
          "repo": "nixpkgs",
          "rev": "1c21dea52279ba45e4b00107f532c6c6116dca00",
          "type": "github"
        },
        "original": {
          "owner": "nixos",
          "ref": "release-22.05",
          "repo": "nixpkgs",
          "type": "github"
        }
      },
      "nixpkgs-darwin": {
        "locked": {
          "lastModified": 1666401273,
          "narHash": "sha256-AG3MoIjcWwz1SPjJ2nymWu4NmeVj9P40OpB1lsmxFtg=",
          "owner": "nixos",
          "repo": "nixpkgs",
          "rev": "3933d8bb9120573c0d8d49dc5e890cb211681490",
          "type": "github"
        },
        "original": {
          "owner": "nixos",
          "ref": "nixpkgs-22.05-darwin",
          "repo": "nixpkgs",
          "type": "github"
        }
      },
      "nixpkgs-unstable": {
        "locked": {
          "lastModified": 1666424192,
          "narHash": "sha256-rb/a7Kg9s31jqkvdOQHFrUc5ig5kB+O2ZKB8mjU2kW8=",
          "owner": "nixos",
          "repo": "nixpkgs",
          "rev": "4f8287f3d597c73b0d706cfad028c2d51821f64d",
          "type": "github"
        },
        "original": {
          "owner": "nixos",
          "ref": "nixpkgs-unstable",
          "repo": "nixpkgs",
          "type": "github"
        }
      },
      "root": {
        "inputs": {
          "darwin": "darwin",
          "home-manager": "home-manager",
          "nixpkgs": "nixpkgs",
          "nixpkgs-darwin": "nixpkgs-darwin",
          "nixpkgs-unstable": "nixpkgs-unstable"
        }
      }
    },
    "root": "root",
    "version": 7
  },
  "original": {
    "submodules": true,
    "type": "git",
    "url": "file:///Users/n8henrie/.dotfiles"
  },
  "originalUrl": "git+file:///Users/n8henrie/.dotfiles",
  "path": "/nix/store/mxm1s1vwabpr3g5pp061zly7myxccpxm-source",
  "resolved": {
    "submodules": true,
    "type": "git",
    "url": "file:///Users/n8henrie/.dotfiles"
  },
  "resolvedUrl": "git+file:///Users/n8henrie/.dotfiles",
  "revCount": 863,
  "revision": "3afc1004fa37b760e66183519c79458843e7d533",
  "url": "git+file:///Users/n8henrie/.dotfiles?ref=refs%2fheads%2fmaster&rev=3afc1004fa37b760e66183519c79458843e7d533"
}
```

Which makes my `.url`: `"git+file:///Users/n8henrie/.dotfiles?ref=refs%2fheads%2fmaster&rev=3afc1004fa37b760e66183519c79458843e7d533"`

which gets set to `$flake`, and so the `nix build` call is eventually:

```
$ nix --extra-experimental-features 'nix-command flakes' build 'git+file:///Users/n8henrie/.dotfiles?ref=refs%2fheads%2fmaster&rev=3afc1004fa37b760e66183519c79458843e7d533?submodules=1#darwinConfigurations.NatePro.system'
error: hash '3afc1004fa37b760e66183519c79458843e7d533?submodules=1' has wrong length for hash type 'sha1'
```

Obviously the `?submodules` needs to be `&submodules` at this point.

Added another commit that adopts an "official" regex for parsing the flake url  and does a better job preserving `?submodules=1` vs `&submodules=1` based on the output of `nix flake metadata --json | jq -r '.resolved.submodules'`

**Comment by n8henrie** [comment]
Rebased on master

**Comment by lockejan** [comment]
Thanks for the PR. I've tested it on my machine, because I've recently switched to flakes.
I'm running into two errors.
The first one is because nix-darwin tries to generate the manpage, which fails, I don't know why.
The default of `documentation.enable` is true. Changing it to false, "fixed" it. Have you disabled it as well?

The second error is interesting. I have two submodules in my dotfiles. The first one works with your patch and only contains files which are then symlinked through the evaluation.
The second submodule contains nix files which are imported as modules in home-manager.
I'm only facing the error during 
`darwin-rebuild switch --flake ".?submodules=1#m1"`
but  not during
 `nix build '.?submodules=1#darwinConfigurations.m1.system'`.

**Comment by n8henrie** [comment]
Thanks for the feedback. Can you post the error message, or a link to the code that's causing the error (if open source)?

yes, I think I have documentation disabled, but this was due to a different error (I'll see if I can find the issue).

**Comment by lockejan** [comment]
> Thanks for the feedback. Can you post the error message, or a link to the code that's causing the error (if open source)?
> 
> yes, I think I have documentation disabled, but this was due to a different error (I'll see if I can find the issue).
> 
> EDIT: #555

```shell
nix build '.?submodules=1#darwinConfigurations.m1.system'
warning: Git tree '/Users/lockejan/dotfiles' is dirty
error: getting status of '/nix/store/j2lfvdhxi6hdvb50pk8p6npngf1symlv-source/home-manager/machines': No such file or directory
```

My dotfiles are public, but I removed this specific submodule in [my current flake branch ](https://github.com/lockejan/nix-dotfiles/tree/flakes)and added those files directly to mitigate that error for now.
The folder `machines` is a git-submodule folder, containing personal.nix and work.nix 


In case of setting `documentation.enable=true`, the current master evaluates without errors, while your suggested changes are resulting in a failed build and the following errors -> [error.log](https://github.com/LnL7/nix-darwin/files/10147321/error.log)

**Comment by n8henrie** [comment]
@lockejan I have `documentation.enable` unset and mine builds without issue. I inserted it and it builds without error with both `false` and `true`. ¯\\\_(ツ)_/¯

That error looks a *lot* like the one I was getting that was from an issue in nixpkgs which has since been resolved. Have you tried updating your flake inputs for `nixpkgs`?

**Comment by n8henrie** [comment]
Cloning your repo and building the `flakes` branch, I get an error -- looks like `personal.nix` might be encrypted?

```console
$ darwin-rebuild build --flake .?submodules=1#m1
building the system configuration...
error: syntax error, unexpected end of file

       at /nix/store/8172nycvv9xbvk0k798lsgwg6fz6k0pd-source/home-manager/machines/personal.nix:1:1:

            1| GITCRYPTW__lS@>2)cG{(s8h]2
                                         ^bEY]s17SPE
                                                                A5X48?Y"Apmo;/+o|E}2TaPާ)  iS27?Xg
                                                                                                 zVS\rC_薶væ[pW1
             | ^
hn7"YxB:2.E?Ϝ+M3'DOs#k_D{ATx?y\Z'*~0#̣T!zWx>:Za#Je׳(Y5c̉,\1:F"a$\%\:نg޽p=m̚=8
/fƳQgYr,J,28Eۍ!ZUDf0ڂoM=]RG&m՗=:qN9d49
   &
(use '--show-trace' to show detailed location information)
$ file home-manager/machines/personal.nix
home-manager/machines/personal.nix: data
```

**Comment by lockejan** [comment]
> Cloning your repo and building the `flakes` branch, I get an error -- looks like `personal.nix` might be encrypted?
> 
> ```
> $ darwin-rebuild build --flake .?submodules=1#m1
> building the system configuration...
> error: syntax error, unexpected end of file
> 
>        at /nix/store/8172nycvv9xbvk0k798lsgwg6fz6k0pd-source/home-manager/machines/personal.nix:1:1:
> 
>             1| GITCRYPTW__lS@>2)cG{(s8h]2
>                                          ^bEY]s17SPE
>                                                                 A5X48?Y"Apmo;/+o|E}2TaPާ)  iS27?Xg
>                                                                                                  zVS\rC_薶væ[pW1
>              | ^
> hn7"YxB:2.E?Ϝ+M3'DOs#k_D{ATx?y\Z'*~0#̣T!zWx>:Za#Je׳(Y5c̉,\1:F"a$\%\:نg޽p=m̚=8
> /fƳQgYr,J,28Eۍ!ZUDf0ڂoM=]RG&m՗=:qN9d49
>    &
> (use '--show-trace' to show detailed location information)
> $ file home-manager/machines/personal.nix
> home-manager/machines/personal.nix: data
> ```

That's correct. It mostly contains additional configs I don't want to expose. Anyway, you could just comment the module reference to make the flake build without access to the encrypted stuff. It doesn't contain any required stuff.

**Comment by n8henrie** [comment]
I needed to push the rebase to my fork, and you heed to use the `issue_549` branch.

```
$ nix flake lock --update-input darwin   
$ git diff
diff --git a/darwin/configuration.nix b/darwin/configuration.nix
index 5dc72cf..eb310f7 100644
--- a/darwin/configuration.nix
+++ b/darwin/configuration.nix
@@ -196,7 +196,7 @@ in
   # programs.nix-index.enable = true;
   nixpkgs.config.allowUnfree = true;
 
-  documentation.enable = false;
+  documentation.enable = true;
   # Fonts
   fonts.fontDir.enable = true;
   fonts.fonts = with pkgs; [
diff --git a/darwin/work-configuration.nix b/darwin/work-configuration.nix
index 63f5ee9..a580172 100644
--- a/darwin/work-configuration.nix
+++ b/darwin/work-configuration.nix
@@ -10,7 +10,7 @@
   # $ nix-env -qaP | grep wget
   environment.systemPackages = with pkgs; [ vim ];
 
-  documentation.enable = false;
+  documentation.enable = true;
 
   homebrew = {
     enable = true;
diff --git a/flake.lock b/flake.lock
index 37f8037..bd71718 100644
--- a/flake.lock
+++ b/flake.lock
@@ -7,15 +7,16 @@
         ]
       },
       "locked": {
-        "lastModified": 1665392861,
-        "narHash": "sha256-bCd8fYJMAb0LzabsiXl4nxECDoz483bJOCa2hjox7N0=",
+        "lastModified": 1670860643,
+        "narHash": "sha256-kXYSTxkuqgoYhpbeCO47IgDaxYjwdPhpRDQcl1eEttk=",
         "owner": "n8henrie",
         "repo": "nix-darwin",
-        "rev": "ef56fd8979b5f4e800c4716f62076e00600b1172",
+        "rev": "8e47c94aaebc233fa532884691842b82df56c056",
         "type": "github"
       },
       "original": {
         "owner": "n8henrie",
+        "ref": "issue_549",
         "repo": "nix-darwin",
         "type": "github"
       }
diff --git a/flake.nix b/flake.nix
index 4f1c509..9043bda 100644
--- a/flake.nix
+++ b/flake.nix
@@ -8,7 +8,7 @@
     nixpkgs-nixos.url = "github:NixOs/nixpkgs/nixos-22.11";
 
     # darwin.url = "github:lnl7/nix-darwin";
-    darwin.url = "github:n8henrie/nix-darwin";
+    darwin.url = "github:n8henrie/nix-darwin?ref=issue_549";
     darwin.inputs.nixpkgs.follows = "nixpkgs-unstable";
 
     home-manager.url = "github:nix-community/home-manager";
@@ -60,7 +60,7 @@
                   ./home-manager/modules/python.nix
                   # ./home-manager/modules/ssh.nix
                   ./home-manager/modules/tmux.nix
-                  ./home-manager/machines/personal.nix
+                  # ./home-manager/machines/personal.nix
                 ];
               # inherit pkgs;
             }
$ darwin-rebuild build --flake .?submodules=1#m1
warning: Git tree '/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.cScIS3iB4O/nix-dotfiles' is dirty
building the system configuration...
warning: Git tree '/private/var/folders/kb/tw_lp_xd2_bbv0hqk4m0bvt80000gn/T/tmp.cScIS3iB4O/nix-dotfiles' is dirty
$ echo $?
0
```

**Comment by lockejan** [comment]
> darwin.url = "github:n8henrie/nix-darwin?ref=issue_549";

Thanks for the update. Builds on my machine as well. 👍
It would be nice to have a test against your regex to ensure that nothing else breaks IMHO.

**Comment by n8henrie** [comment]
I agree, it seems like a test would be nice, but I'm not sure how one would be implemented in this case.

All of the existing tests seem to change some configuration parameter and then ensure that it works, but this change doesn't modify any nix-darwin config, just ensures that the submodules flag is passed on to `nix`.

I'm open to ideas on how a test would work in this case and happy to add that into the PR. For example I could add something to the GitHub Actions tests: https://github.com/LnL7/nix-darwin/blob/master/.github/workflows/test.yml -- just a test showing that an installation that uses submodules builds.

**Comment by n8henrie** [comment]
I don't know if this is the *best* way, but I added an extra test to the GitHub Actions that tries to build a flake that depends on a file contained in a git submodule.

The test is expected to fail if run as `darwin-rebuild build --flake /path/to/repo#simple` or with `... ?submodules=0#simple` but succeed with `... ?submodules=1#simple`

Seems to be working as intended.

**Comment by lockejan** [comment]
> I don't know if this is the *best* way, but I added an extra test to the GitHub Actions that tries to build a flake that depends on a file contained in a git submodule.
> 
> 
> 
> The test is expected to fail if run as `darwin-rebuild build --flake /path/to/repo#simple` or with `... ?submodules=0#simple` but succeed with `... ?submodules=1#simple`
> 
> 
> 
> Seems to be working as intended.
> 
> 
> 
> EDIT: The most immediate / straightforward approach I could think of was to just copy the existing `simple.nix` and related `flake.nix` to a new directory, initialize as a repo, create a second repo to use as a submodule, `git submodule add`, and then run a quick and dirty `sed` regex to add a dependency on the second repo.
> 
> 
> 
> If it looks like this PR is likely to be merged, I'd be happy to try to simplify the test by splitting `simple.nix` into a separate test file and modifying `flake.nix` to have a separate output used only for testing the submodule integration... if that would be helpful!

Cool. Thank you for adding those tests. Having also a nix build example as part of the tests would propagate breaking changes in the flakes interface directly, but that's debatable. 

LGTM as it is now👍

@domenkozar @LnL7 any suggestions from your side?

**Comment by lockejan** [comment]
> This continues to work well for me. Now that the holidays are over, is there anything else I can do to help push this forward?
> 
> Any feedback on my approach to the test?

Using this as well without any issues so far.

Can we merge? @domenkozar @LnL7

**Review by domenkozar — APPROVED** [review]

**Comment by reckenrode** [comment]
This change broke using a `github:` references to build a flake.

```
$ darwin-rebuild build --flake github:reckenrode/nixos-configs
error: cannot find flake 'flake:githubreckenrode/nixos-configs' in the flake registries
```

**Comment by n8henrie** [comment]
@reckenrode sorry about that. Care to open a new issue, and I'll try to sort out where I went wrong?

**Comment by reckenrode** [comment]
Thanks for the quick reply. I opened #628 for the issue.

**Pull request merged**
