### PR TITLE
chore: remove deprecations for mkPackageOptionMD

### PR DESCRIPTION
**Pull request by nklmilojevic**
mkPackageOptionMD will be deprecated in nix 25.05, changing it to reflect this.

### CODE REVIEW

**Review by Samasaur1 — CHANGES_REQUESTED** [review]
You're removing `mkPackageOptionMD` from the `inherit` statement, but not from where it's actually used  (line 27)

**Review by Enzime — APPROVED** [review]
LGTM

Can you squash it into one commit?

**Comment by nklmilojevic** [comment]
whoops, I did a wrong force push. Let me open up a normal PR, this one is not in good condition, apologies.

**Comment by nklmilojevic** [comment]
https://github.com/LnL7/nix-darwin/pull/1011 added a new PR here

**Pull request closed without merging**
