### PR TITLE
Support the Apple Silicon Homebrew directory

### PR DESCRIPTION
**Pull request by weihua-lu**
matchai's PR fix https://github.com/LnL7/nix-darwin/pull/301 would still fail on silicon brew due to path issue, made a quick fix based on that one.

### CODE REVIEW

**Review by LnL7 — COMMENTED** [review]
Perhaps #303 is a nicer alternative, for which the default can be replaced with a state version bump at some point? The disadvantage is that this will need to be configured explicitly for now.

**Comment by malob** [comment]
Yeah, my guess is that doing something like #304 makes the most sense here.

**Comment by malob** [comment]
Actually, my guess is that figuring out exactly what the "right" thing to do if any with #304, might take a little more discussion. Given that this PR fixes the current issue, and it's easy to make further changes later, I'd suggest this PR be merged now so that there's a fix available for this issue sooner rather than later.

**Comment by malob** [comment]
@LnL7, just a heads up that this PR can likely be closed since #304 was merged.

**Pull request closed without merging**
