### PR TITLE
skhd: add package to path

### PR DESCRIPTION
**Pull request by MaxSchlueter**
----

#

### CODE REVIEW

**Comment by LnL7** [comment]
Why do you need to have the binary available?

**Comment by MaxSchlueter** [comment]
For convenience. I need to reload skhd manually after the config file has changed and I'm also using the `--observe` option to find out keycodes.

**Comment by gshpychka** [comment]
@LnL7 any reason not to merge this?

**Comment by Enzime** [comment]
@MaxSchlueter thanks for the PR, it looks good to me, just needs a rebase for the tests to run

**Comment by Enzime** [comment]
Superseded by #1104

**Pull request closed without merging**
