### PR TITLE
fonts: Adds support if Nix is on another filesystem.

### PR DESCRIPTION
**Pull request by tricktron**
On Catalina, the default way is to install Nix on a new volume which breaks hardlinking the font files. If that is the case I just copy them.

### CODE REVIEW

**Comment by jacereda** [comment]
There's a grep in `tests/fonts.nix` that is probably affected by this?

**Comment by tricktron** [comment]
@jacereda Nice catch. Thank you. I fixed the test.

**Comment by kreisys** [comment]
Is this the last issue affecting Catalina?

**Comment by tricktron** [comment]
@kreisys Besides the fonts everything runs smoothly for me on Catalina.

**Comment by kreisys** [comment]
> @kreisys Besides the fonts everything runs smoothly for me on Catalina.

Sweet. I guess I'll watch this PR then.

**Comment by tricktron** [comment]
@LnL7 I replaced `mv` with `rsync` to prevent partial copies.

**Comment by uosis** [comment]
I can also confirm that I did not encounter other issues on Catalina.

**Comment by kreisys** [comment]
Me neither... have been using this on Catalina for several weeks now.

**Pull request merged**
