### PR TITLE
defaults: Add options for dragOnGesture feature

### PR DESCRIPTION
**Pull request by 2gn**
#463

### CODE REVIEW

**Comment by 2gn** [comment]
Could someone please review this PR? It's been around 6 months.

**Comment by MoritzR** [comment]
I find this option useful, is there any way this can be merged?

**Comment by Enzime** [comment]
@2gn could you rebase your PR on top of master?

**Comment by 2gn** [comment]
@Enzime @MoritzR 
Sorry, my computer is (physically) broken right now and I cannot access it. I will close this pull request so please open a new one.

**Pull request closed without merging**
