### PR TITLE
treewide: remove lib.mdDoc

### PR DESCRIPTION
**Pull request by wegank**
`lib.mdDoc` has been removed in NixOS/nixpkgs#303841.

### CODE REVIEW

**Comment by wegank** [comment]
Oh, stable means 23.05, not 23.11...

**Comment by purcell** [comment]
> Oh, stable means 23.05, not 23.11...

Presumably we'd want to bump the stable channel [here](https://github.com/LnL7/nix-darwin/blob/36524adc31566655f2f4d55ad6b875fb5c1a4083/.github/workflows/test.yml#L7) for the purpose of GitHub Actions?

**Comment by yonkeltron** [comment]
This seems to work great in terms of fixing that bug, so great job. I was able to install nix-darwin using the flake method on a clean installation of macOS Sonoma 14.4.1 (23E224).

On my clean install, I noticed that it seems like `pkg-config` is broken. For example, I have several development libraries installed via my `flake.nix` and yet they aren't findable:

```shell
~ via 🐍 v3.11.8
❯ pkg-config --list-all

~ via 🐍 v3.11.8
❯ pkg-config --libs libsodium
Package libsodium was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsodium.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsodium' found

~ via 🐍 v3.11.8
❯ echo $PKG_CONFIG_PATH


``` 

Not sure if related, so asking for guidance if I should open a separate issue.

**Comment by nwjsmith** [comment]
@yonkeltron I don't think that's related, you should open a new issue. FWIW on a fresh `nix shell` I also see the same behaviour:

```
$ nix shell nixpkgs#libsodium nixpkgs#pkg-config
$ pkg-config --libs libsodium
Package libsodium was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsodium.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsodium' found

**Comment by yonkeltron** [comment]
> @yonkeltron I don't think that's related, you should open a new issue. 

You got it! I opened https://github.com/LnL7/nix-darwin/issues/934 and that should do it.

Love,
+Jonathan

**Review by tarc — APPROVED** [review]
I just updated my setup here to use `github:wegank/nix-darwin/mddoc-remove` and it fixed the error I was getting after flake update:

```output
error: attribute 'mdDoc' missing
```

**Comment by dominikb1888** [comment]
@tarc: Can confirm the approach below works for me as well.

> I just updated my setup here to use `github:wegank/nix-darwin/mddoc-remove` and it fixed the error I was getting after flake update:
> 
> ```
> error: attribute 'mdDoc' missing
> ```

**Comment by na-son** [comment]
Working for me as well https://github.com/na-son/nixos-config/commit/b3e2ff5b043d05b09fd3584d5222bde29da10749

**Comment by hesthub** [comment]
Another working build here using `github:wegank/nix-darwin/mddoc-remove`

**Comment by purcell** [comment]
^ it'll work now even without it if you also update to the latets nixpkgs-unstable.

**Review by Enzime — APPROVED** [review]
LGTM

**Pull request merged**
