### PR TITLE
flakes: Do not verify channels when using flakes.

### PR DESCRIPTION
**Pull request by jsoo1**
#403

### CODE REVIEW

**Review by LnL7 — DISMISSED** [review]
I think this check is still relevant regardless of how you build your system, this check only fires if the channels both exist and point to an unexpected location.

The goal here was to attempt to notice when someone has used `sudo nix-channel --update` which (if not still the case) could mess up your local channel references.

**Comment by jsoo1** [comment]
It's been a while and I had to back track from using flakes. But if memory serves, if the system has no channels at all, the check will fail and just not activate the system at all.

**Comment by jsoo1** [comment]
In any case, when using flakes, nix-darwin won't even refer to a channel, correct?

**Comment by socksy** [comment]
After a full night's sleep I solved it! :)

I was doing 
```bash
sudo rm -r ~/.nix-channels
nix-channel --update
```

which would error out when I did `darwin-rebuild switch --flake ".#"` with a `symlink does not point your users channels, aborting activation`.

I solved it last night by just doing `sudo darwin-rebuild switch --flake ".#"`, which was not ideal. Now I looked closer, and saw that the second time around I was actually getting the error that `~/.nix-defexpr/channels` was pointing at the wrong thing. The solution simply was to 

```bash
sudo rm -r  ~/.nix-defexpr/channels
nix-channel --update
```

and now the darwin-rebuild works again

**Comment by yangm97** [comment]
LGTM. Can we get this merged?

**Comment by Enzime** [comment]
@domenkozar just ran into this issue, any chance you can take a look at this PR?

**Comment by domenkozar** [comment]
@jsoo1 could you rebase?

**Comment by jsoo1** [comment]
Sure. It's been a bit since I thought about this one. One sec...

**Review by Enzime — APPROVED** [review]
LGTM

**Comment by emilazy** [comment]
Note that https://github.com/LnL7/nix-darwin/pull/723 ended up effectively reverting this, due to https://github.com/LnL7/nix-darwin/pull/723#discussion_r1257442026. Hopefully if people start having this problem again we can figure out what's causing it or else re-disable the check.

**Pull request merged**
