### PR TITLE
Fix flake reference support

### LINKED ISSUE #628: darwin-rebuild can’t find nix flake references
When I try to build my flake using a flake reference, it fails to find the flake.

This looks like it might have been an accidental regression when fixing #549.

```
$ darwin-rebuild build --flake github:reckenrode/nixos-configs
error: cannot find flake 'flake:githubreckenrode/nixos-configs' in the flake registries
```

### PR DESCRIPTION
**Pull request by reckenrode**
Fixes #628. I added a test that uses a URI with a scheme.

@n8henrie Pinging you since you worked on the submodule support and replied to my comment in the PR.

### CODE REVIEW

**Comment by konradmalik** [comment]
just fyi, the issue is a duplicate of https://github.com/LnL7/nix-darwin/issues/597 and the fix is already implemented in https://github.com/LnL7/nix-darwin/pull/600 since January

**Comment by reckenrode** [comment]
Thanks for the heads up. I can close my PR in favor of yours since it already fixes the issue. Would it be a good idea to cherry pick the added test into that PR?

**Comment by reckenrode** [comment]
Closing as a dupe of #600.

**Comment by konradmalik** [comment]
> Thanks for the heads up. I can close my PR in favor of yours since it already fixes the issue. Would it be a good idea to cherry pick the added test into that PR?

sure, will do it later today

**Pull request closed without merging**
