### PR TITLE
Replace etc files with links if they exist but backup first

### LINKED ISSUE #149: Allow enforcing linking etc when file exists
```
warning: not linking environment.etc."nix/nix.conf" because /etc/nix/nix.conf exists, skipping...
```

In some situations it's desireable to override etc files if they exist. For example when you install Nix and then nix-darwin, it won't take over nix.conf.

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes #149

### CODE REVIEW

**Comment by LnL7** [comment]
I added some extra validation for nix.conf in 4bffc92, this should be relatively safe if the uninstaller restores the backup files.

**Comment by domenkozar** [comment]
Thanks :)

**Comment by domenkozar** [comment]
- [ ] move all backup files back to original location on uninstall

**Comment by kclejeune** [comment]
@LnL7 Is this alright to merge? The installer in its current state doesn't have `darwin-rebuild` available in the path if you install nix-darwin immediately after installing nix.

**Comment by domenkozar** [comment]
I've used this in production quite a few times and it works.

**Comment by kclejeune** [comment]
> I've used this in production quite a few times and it works.

It looks good to me, this is pretty much the same process I did manually to get the install to work.  Does this also have the update to restore backed up files using the uninstaller?

**Comment by kradalby** [comment]
I run into this with `/etc/shells` quite a bit, would this still be a candidate for merger?

**Comment by kclejeune** [comment]
> I run into this with `/etc/shells` quite a bit, would this still be a candidate for merger?

This doesn't work in its current state anymore, but my work in #257 does. 

When I originally opened it, @LnL7 requested finer controls over which files are backed up, but I didn't have time to fix that at the time. I can revisit it to fix that and open the PR again.

**Comment by kradalby** [comment]
@kclejeune that would be great 👍

**Pull request closed without merging**
