### PR TITLE
linux-builder: add maxJobs option

### LINKED ISSUE #751: `nix.linux-builder` needs a `maxJobs` configuration
The new `nix.linux-builder` module is great, but it has no way to customize the `nix.buildMachines` entry. In particular, I can't set the `maxJobs` key, which means it defaults to 1 job at a time. This is rather unfortunate as I'm configuring my builder to use multiple cores and so I want to be able to dispatch multiple jobs at a time to it. I don't know if there are any other knobs on the builder that should be exposed for configuration, but `maxJobs` definitely should be.

Incidentally, speaking of the builder, it doesn't set `protocol`, and so it defaults to `ssh`; perhaps it should be setting `protocol = "ssh-ng"` as well?

### PR DESCRIPTION
**Pull request by lilyball**
Fixes #751

### CODE REVIEW

**Review by Enzime — APPROVED** [review]
LGTM

**Comment by emilazy** [comment]
It looks like the VM unconditionally uses 1 core, maybe we could set that based on this option? Not sure if that would cause problematic rebuilds.

**Comment by lilyball** [comment]
@emilazy I'm not opposed to the idea of defaulting `virtualisation.cores` to this value, but I don't have enough experience here to know if it's a reasonable assumption that the maximum number of jobs should match the number of cores. I also don't know if that will cause a rebuild (I hope not, I hope it just changes the configuration passed to qemu on the host, but I haven't dug into this).

**Comment by lilyball** [comment]
Another idea is to just change the example for `nix.linux-builder.modules` to set `virtualisation.cores` instead of `virtualisation.darwin-builder.hostPort` (especially since setting `hostPort` right now will not work with the generated ssh config).

**Pull request merged**
