### PR TITLE
Rename fonts.fonts -> fonts.packages

### PR DESCRIPTION
**Pull request by b-**
Is this all that's necessary for #752? I've never done this before, but it looks like the only change that was necessary to do the same on NixOS (https://github.com/NixOS/nixpkgs/commit/5162df32399c7e9d77cc38702202983dbe9ad113)

I did _not_ test this, which is why it's marked as draft. (I suppose I can by pointing my flake.nix to the fork in this pr, right?)

### CODE REVIEW

**Comment by b-** [comment]
Sorry, I have no idea how I closed this. I think I meant to convert from a draft to a regular PR and clicked the wrong button…

**Comment by mattpolzin** [comment]
> I suppose I can by pointing my flake.nix to the fork in this pr, right?

Yup, e.g. (for a flake config)
```diff
-    nix-darwin.url = "github:LnL7/nix-darwin";
+    nix-darwin.url = "github:b-/nix-darwin/patch-1";
```

I tested this and it definitely works, though you see a few trace warnings about using deprecated `fonts.fonts` even if you've switched your own config over to `fonts.packages`. I didn't spend the time to track down where those other `fonts.fonts` references live but I suppose at the least it is worth switching the remaining references in this repo over (https://github.com/search?q=repo%3ALnL7%2Fnix-darwin%20fonts.fonts&type=code).

**Comment by b-** [comment]
> > I suppose I can by pointing my flake.nix to the fork in this pr, right?
> 
> Yup, e.g. (for a flake config)
> 
> ```diff
> -    nix-darwin.url = "github:LnL7/nix-darwin";
> +    nix-darwin.url = "github:b-/nix-darwin/patch-1";
> ```
> 
> I tested this and it definitely works, though you see a few trace warnings about using deprecated `fonts.fonts` even if you've switched your own config over to `fonts.packages`. I didn't spend the time to track down where those other `fonts.fonts` references live but I suppose at the least it is worth switching the remaining references in this repo over ([github.com/search?q=repo%3ALnL7%2Fnix-darwin%20fonts.fonts&type=code](https://github.com/search?q=repo%3ALnL7%2Fnix-darwin%20fonts.fonts&type=code)).

Thanks, I was wondering why I was still getting those messages. I’ll change those later today.

**Comment by b-** [comment]
I needed to really force my local machine to refresh the inputs before it stopped showing the warning, (`nix build .\#darwinConfigurations.bri@x86_64-darwin.system --refresh -vvv` but i think it's good now!

**Comment by b-** [comment]
Actually I'm still getting ```trace: Obsolete option `fonts.fonts' is used. It was renamed to `fonts.packages'.``` when building. I'm not sure why…

**Comment by cmacrae** [comment]
I'd also like to see this change integrated 🙏   
for now, I'm using this silly hack (in case anyone else finds it useful):
```nix
fonts =
    let
      fnts = with pkgs; [
        eb-garamond
        emacs-all-the-icons-fonts
        etBook
        fira-code
        font-awesome
        nerdfonts
        roboto
        roboto-mono
      ];
    in
    # TODO: hack to get around waiting for nix-darwin#870
    ({ fontDir.enable = true; }
      // mkIf isLinux { packages = fnts; }
      // mkIf isDarwin { fonts = fnts; });
```

**Comment by emilazy** [comment]
Closing now that #754 is finally merged. Sorry to have prompted this by leaving it dormant for so long, and thank you for taking the initiative!

**Pull request closed without merging**
