### PR TITLE
Add Stage Manager (com.apple.WindowManager) settings as system.defaults.windowmanager

### PR DESCRIPTION
**Pull request by AlexOwl**

### CODE REVIEW

**Review by malob — COMMENTED** [review]
To keep with the naming convention of other `system.defaults` options, I think `windowmanager` should be changed to `WindowManager`.

**Comment by arulagrawal** [comment]
Hi, sorry to bump, but I noticed this PR has been sitting idle for over a year. Maybe @AlexOwl could quickly make the required change or if they are unavailable someone else could?

**Comment by clempat** [comment]
I found this pull request while searching for the `defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false` option to enhance my experience with Yabai. Can you provide an update on adding WindowManager to the project and whether this option will be included?

**Comment by Enzime** [comment]
Superseded by #1002

**Pull request closed without merging**
