### PR TITLE
fish: add package option

### PR DESCRIPTION
**Pull request by adamcstephens**
I want to start testing the new beta and this override seems necessary for full testing.

### CODE REVIEW

**Review by Samasaur1 — APPROVED** [review]

**Comment by adamcstephens** [comment]
Failing test seems unrelated.

**Comment by adamcstephens** [comment]
Mind reviewing @emilazy ?

**Review by Enzime — CHANGES_REQUESTED** [review]
Can you rebase this on the latest master?

**Review by Enzime — APPROVED** [review]
LGTM

Thanks for the contribution

**Comment by adamcstephens** [comment]
Thanks!

**Pull request merged**
