### PR TITLE
Add system terminfo to TERMINFO_DIRS by default

### PR DESCRIPTION
**Pull request by n8henrie**
Fixes https://github.com/LnL7/nix-darwin/issues/543

### CODE REVIEW

**Comment by domenkozar** [comment]
Seems like nixpkgs-unstable channel is still broken, hopefully it updates soon to fix the CI failure.

**Comment by n8henrie** [comment]
Is this waiting on anything other than the install-flake test to pass?

**Comment by ivankovnatsky** [comment]
Not sure yet how, but this change: https://github.com/LnL7/nix-darwin/pull/553/commits/ed993c5038330c9dc0caf08bef7b64fc2f942f75 messes italic font in tmux. Maybe I'm using wrong terminal: `xterm-256color`.

**Comment by lockejan** [comment]
> Not sure yet how, but this change: [ed993c5](https://github.com/LnL7/nix-darwin/commit/ed993c5038330c9dc0caf08bef7b64fc2f942f75) messes italic font in tmux. Maybe I'm using wrong terminal: `xterm-256color`.

Could you reproduce a working italic setup in tmux without this commit?

**Comment by n8henrie** [comment]
https://github.com/tmux/tmux/wiki/FAQ

> Inside tmux TERM must be "screen", "tmux" or similar (such as "tmux-256color").
Don't bother reporting problems where it isn't!

You might try tmux-256color. I don't think I use italics in my terminal, but I'll give it a shot.

**Comment by ivankovnatsky** [comment]
> > Not sure yet how, but this change: [ed993c5](https://github.com/LnL7/nix-darwin/commit/ed993c5038330c9dc0caf08bef7b64fc2f942f75) messes italic font in tmux. Maybe I'm using wrong terminal: `xterm-256color`.
> 
> Did you reproduce a working tmux italic setup without this commit?

yes, running with `env TERM=tmux-256color tmux` does the trick.

**Pull request merged**
